name: Deploy Hugo Blog to GitHub Pages
# 新增权限配置
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库源码
        uses: actions/checkout@v4

      - name: 安装Hugo扩展版
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: 构建静态网页
        run: hugo --baseURL "https://Robin-060.github.io/"

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public